---
- hosts: all
  become: true
  pre_tasks:

  - name: update repository index (CentOS)
    tags: always update
    dnf:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "CentOS"

  - name: install updates (Ubuntu)
    tags: always update
    apt:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Ubuntu"

- hosts: ubuntu
  become: true
  roles:
    - ubuntu_elk

- hosts: centos
  become: true
  roles:
    - centos_elk

