  - name: Selinux Permissive CentOS remote server
    selinux:
      policy: targeted
      state: permissive
    when: ansible_os_family == "RedHat"

  - name: Update sysctl
    sysctl:
      name: vm.max_map_count
      value: "262144"
      sysctl_set: yes

  - name: Add a user
    user:
      name: elasticsearch
      comment: elasticsearch user

  - name: Create a directory
    file:
      path: /data
      state: directory
      mode: 0777

  - name: Install ElasticSearch
    get_url:
      url: https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.8.15.tar.gz
      dest: /data/elasticsearch-6.8.15.tar.gz
      mode: 0755

  - name: Extract ElasticSearch
    unarchive:
      src: /data/elasticsearch-6.8.15.tar.gz
      dest: /data/
      remote_src: yes
      creates: /data/elasticsearch-6.8.15/config/elasticsearch.yml

  - name: Insert ElasticSearch systemd
    template:
      src: elasticsearch.service.j2
      dest: /etc/systemd/system/elasticsearch.service
      mode: 0644

  - name: Insert ElasticSearch config
    template:
      src: elasticsearch.yml.j2
      dest: /data/elasticsearch-6.8.15/config/elasticsearch.yml
      mode: 0660

  - file:
      path: /data/elasticsearch-6.8.15
      owner: elasticsearch
      group: elasticsearch
      recurse: yes

  - name: Reload the Daemon
    systemd:
      daemon_reload: yes

  - name: Start ElasticSearch
    service:
      name: elasticsearch
      state: started
      enabled: yes

  ## Kibana

  - name: Create directory
    file:
      path: /data
      state: directory
      mode: 0777

  - name: Install Kibana
    get_url:
      url: https://artifacts.elastic.co/downloads/kibana/kibana-6.8.15-linux-x86_64.tar.gz
      dest: /data/kibana-6.8.15-linux-x86_64.tar.gz
      mode: 0755

  - name: Extract Kibana
    unarchive:
      src: /data/kibana-6.8.15-linux-x86_64.tar.gz
      dest: /data/
      remote_src: yes
      creates: /data/kibana-6.8.15-linux-x86_64/config/kibana.yml

  - name: Insert Kibana unit file
    template:
      src: kibana.yml.j2
      dest: /etc/systemd/system/kibana.service
      mode: 0644

  - name: Insert config template
    template:
      src: kibana.yml.j2
      dest: /data/kibana-6.8.15-linux-x86_64/config/kibana.yml
      mode: 0660

  - name: Reload the Daemon
    systemd:
      daemon_reload: yes

## Logstash

  - name: Create a directory
    file:
      path: /data
      state: directory
      mode: "u=rwx,g=rwx,o=rwx"

  - name: Install LogStash
    get_url:
      url: https://artifacts.elastic.co/downloads/logstash/logstash-6.8.15.tar.gz
      dest: /data/logstash-6.8.15.tar.gz
      mode: 0755

  - name: Extract logstash
    unarchive:
      src: /data/logstash-6.8.15.tar.gz
      dest: /data/
      remote_src: yes
      creates: /data/logstash-6.8.15/cof.d/inputs/conf

  - name: Insert LogStash unit file
    template:
      src: logstash.service.j2
      dest: /etc/systemd/system/logstash.service
      mode: 0644

  - name: Start/Stop LogStash
    template:
      src: start.sh.j2
      dest: /data/logstash-6.8.15/start.sh
      mode: 0754

  - name: Create directory
    file:
      path: /data/logstash-6.8.15/conf.d
      state: directory
      mode: 0777

  - name: Update config default
    template:
      src: inputs.conf.j2
      dest: /data/logstash-6.8.15/conf.d/inputs.conf
      mode: 0660

  - name: Daemon Reload
    systemd:
      daemon_reload: yes

  - name: Start LogStash
    service:
      name: logstash
      state: started
      enabled: yes

